version: '3.1'

services:

  db:
    build: 
        context: .
    image: erickagrazal/postgres
    restart: always
    environment:
        POSTGRES_DB: database
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
    ports: 
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
